// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx02Gt2-eujHYKmsIQquOL7eoeuGM8wdk',
    appId: '1:412411715571:web:30b6fac832d1ae49b5fc86',
    messagingSenderId: '412411715571',
    projectId: 'hw4app',
    authDomain: 'hw4app.firebaseapp.com',
    storageBucket: 'hw4app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4vwdl1zPLA7kVseEYY9wpxUb6mC9jnTA',
    appId: '1:412411715571:android:afa5e2424aea04d9b5fc86',
    messagingSenderId: '412411715571',
    projectId: 'hw4app',
    storageBucket: 'hw4app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy-Pg0Glr1qBCnF7UKqmpAajQVvTljHn0',
    appId: '1:412411715571:ios:4d5e26afaa57244bb5fc86',
    messagingSenderId: '412411715571',
    projectId: 'hw4app',
    storageBucket: 'hw4app.firebasestorage.app',
    iosBundleId: 'com.example.hw4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy-Pg0Glr1qBCnF7UKqmpAajQVvTljHn0',
    appId: '1:412411715571:ios:4d5e26afaa57244bb5fc86',
    messagingSenderId: '412411715571',
    projectId: 'hw4app',
    storageBucket: 'hw4app.firebasestorage.app',
    iosBundleId: 'com.example.hw4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx02Gt2-eujHYKmsIQquOL7eoeuGM8wdk',
    appId: '1:412411715571:web:240f0e2cc25f8c1bb5fc86',
    messagingSenderId: '412411715571',
    projectId: 'hw4app',
    authDomain: 'hw4app.firebaseapp.com',
    storageBucket: 'hw4app.firebasestorage.app',
  );
}
